### PR TITLE
WIP: Install button: construct link dynamically

### PR DESCRIPTION
**Pull request by mb21**
Closes https://github.com/jgm/pandoc-website/issues/29

Works with https://github.com/jgm/pandoc/pull/5167

I'll see whether I can get the make script adjusted to include the js... feel free to take over ;-)

### CODE REVIEW

**Comment by jgm** [comment]
OK, I modified the makefile and tweaked the formatting a little. Take a look.

Note that I get an error in the js console: "Failed to load resource: Frame load interrupted"
However, it looks as if the package does download successfully. Not sure why.

**Comment by mb21** [comment]
Cool, thanks. A few things:

- If we load the script in the `<head>` (as opposed to the bottom of the `<body>`), we should not call the function instantly, but instead: `document.addEventListener('load', currentFunction....`
- if we have `for macOS` on the button, it quickly flashes when the text is changed by the js... but maybe that's okay.
- the CSS on the button:
  - `margin: auto` doesn't do anything AFAIK.
  - to prevent the button being wider than the screen on mobile devices: `width` should probably be `max-width` and add `white-space: normal;`

**Comment by jgm** [comment]
screen shot 2018-12-19 at 12 56 06 pm

on Safari

**Comment by mb21** [comment]
Seems to be a Safari issue... something with how the GitHub server advertises the content type etc... but nothing we can fix. It happens also when you go to https://github.com/jgm/pandoc/releases and click on the link there...

**Comment by jgm** [comment]
OK, nothing to worry about then. The package downloads
and installs.

**Pull request merged**
